# TCL File Generated by Component Editor 20.1
# Sat Jan 02 17:20:52 CET 2021
# DO NOT MODIFY


# 
# spin_sensor_receiver "spin_sensor_receiver" v1.0
# giovanny 2021.01.02.17:20:52
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module spin_sensor_receiver
# 
set_module_property DESCRIPTION ""
set_module_property NAME spin_sensor_receiver
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP Salukat
set_module_property AUTHOR giovanny
set_module_property DISPLAY_NAME spin_sensor_receiver
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL spin_sensor_top
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file spin_sensor_top.v VERILOG PATH spin_sensor_top.v TOP_LEVEL_FILE
add_fileset_file axi_ad9361.v VERILOG PATH ../../library/axi_ad9361/axi_ad9361.v
add_fileset_file axi_ad9361_rx.v VERILOG PATH ../../library/axi_ad9361/axi_ad9361_rx.v
add_fileset_file axi_ad9361_rx_channel.v VERILOG PATH ../../library/axi_ad9361/axi_ad9361_rx_channel.v
add_fileset_file axi_ad9361_rx_pnmon.v VERILOG PATH ../../library/axi_ad9361/axi_ad9361_rx_pnmon.v
add_fileset_file axi_ad9361_tdd.v VERILOG PATH ../../library/axi_ad9361/axi_ad9361_tdd.v
add_fileset_file axi_ad9361_tdd_if.v VERILOG PATH ../../library/axi_ad9361/axi_ad9361_tdd_if.v
add_fileset_file axi_ad9361_tx.v VERILOG PATH ../../library/axi_ad9361/axi_ad9361_tx.v
add_fileset_file axi_ad9361_tx_channel.v VERILOG PATH ../../library/axi_ad9361/axi_ad9361_tx_channel.v
add_fileset_file axi_ad9361_alt_lvds_rx.v VERILOG PATH ../../library/axi_ad9361/intel/axi_ad9361_alt_lvds_rx.v
add_fileset_file axi_ad9361_alt_lvds_tx.v VERILOG PATH ../../library/axi_ad9361/intel/axi_ad9361_alt_lvds_tx.v
add_fileset_file axi_ad9361_cmos_if.v VERILOG PATH ../../library/axi_ad9361/intel/axi_ad9361_cmos_if.v
add_fileset_file axi_ad9361_lvds_if.v VERILOG PATH ../../library/axi_ad9361/intel/axi_ad9361_lvds_if.v
add_fileset_file axi_ad9361_lvds_if_10.v VERILOG PATH ../../library/axi_ad9361/intel/axi_ad9361_lvds_if_10.v
add_fileset_file axi_ad9361_lvds_if_c5.v VERILOG PATH ../../library/axi_ad9361/intel/axi_ad9361_lvds_if_c5.v
add_fileset_file ad_3w_spi.v VERILOG PATH ../../library/common/ad_3w_spi.v
add_fileset_file ad_addsub.v VERILOG PATH ../../library/common/ad_addsub.v
add_fileset_file ad_adl5904_rst.v VERILOG PATH ../../library/common/ad_adl5904_rst.v
add_fileset_file ad_axis_inf_rx.v VERILOG PATH ../../library/common/ad_axis_inf_rx.v
add_fileset_file ad_b2g.v VERILOG PATH ../../library/common/ad_b2g.v
add_fileset_file ad_bus_mux.v VERILOG PATH ../../library/common/ad_bus_mux.v
add_fileset_file ad_csc.v VERILOG PATH ../../library/common/ad_csc.v
add_fileset_file ad_csc_CrYCb2RGB.v VERILOG PATH ../../library/common/ad_csc_CrYCb2RGB.v
add_fileset_file ad_csc_RGB2CrYCb.v VERILOG PATH ../../library/common/ad_csc_RGB2CrYCb.v
add_fileset_file ad_datafmt.v VERILOG PATH ../../library/common/ad_datafmt.v
add_fileset_file ad_dds.v VERILOG PATH ../../library/common/ad_dds.v
add_fileset_file ad_dds_1.v VERILOG PATH ../../library/common/ad_dds_1.v
add_fileset_file ad_dds_2.v VERILOG PATH ../../library/common/ad_dds_2.v
add_fileset_file ad_dds_cordic_pipe.v VERILOG PATH ../../library/common/ad_dds_cordic_pipe.v
add_fileset_file ad_dds_sine.v VERILOG PATH ../../library/common/ad_dds_sine.v
add_fileset_file ad_dds_sine_cordic.v VERILOG PATH ../../library/common/ad_dds_sine_cordic.v
add_fileset_file ad_edge_detect.v VERILOG PATH ../../library/common/ad_edge_detect.v
add_fileset_file ad_g2b.v VERILOG PATH ../../library/common/ad_g2b.v
add_fileset_file ad_iobuf.v VERILOG PATH ../../library/common/ad_iobuf.v
add_fileset_file ad_iqcor.v VERILOG PATH ../../library/common/ad_iqcor.v
add_fileset_file ad_mem.v VERILOG PATH ../../library/common/ad_mem.v
add_fileset_file ad_mem_asym.v VERILOG PATH ../../library/common/ad_mem_asym.v
add_fileset_file ad_mux.v VERILOG PATH ../../library/common/ad_mux.v
add_fileset_file ad_mux_core.v VERILOG PATH ../../library/common/ad_mux_core.v
add_fileset_file ad_perfect_shuffle.v VERILOG PATH ../../library/common/ad_perfect_shuffle.v
add_fileset_file ad_pngen.v VERILOG PATH ../../library/common/ad_pngen.v
add_fileset_file ad_pnmon.v VERILOG PATH ../../library/common/ad_pnmon.v
add_fileset_file ad_pps_receiver.v VERILOG PATH ../../library/common/ad_pps_receiver.v
add_fileset_file ad_rst.v VERILOG PATH ../../library/common/ad_rst.v
add_fileset_file ad_ss_422to444.v VERILOG PATH ../../library/common/ad_ss_422to444.v
add_fileset_file ad_ss_444to422.v VERILOG PATH ../../library/common/ad_ss_444to422.v
add_fileset_file ad_sysref_gen.v VERILOG PATH ../../library/common/ad_sysref_gen.v
add_fileset_file ad_tdd_control.v VERILOG PATH ../../library/common/ad_tdd_control.v
add_fileset_file ad_xcvr_rx_if.v VERILOG PATH ../../library/common/ad_xcvr_rx_if.v
add_fileset_file axi_ctrlif.vhd VHDL PATH ../../library/common/axi_ctrlif.vhd
add_fileset_file axi_streaming_dma_rx_fifo.vhd VHDL PATH ../../library/common/axi_streaming_dma_rx_fifo.vhd
add_fileset_file axi_streaming_dma_tx_fifo.vhd VHDL PATH ../../library/common/axi_streaming_dma_tx_fifo.vhd
add_fileset_file dma_fifo.vhd VHDL PATH ../../library/common/dma_fifo.vhd
add_fileset_file pl330_dma_fifo.vhd VHDL PATH ../../library/common/pl330_dma_fifo.vhd
add_fileset_file up_adc_channel.v VERILOG PATH ../../library/common/up_adc_channel.v
add_fileset_file up_adc_common.v VERILOG PATH ../../library/common/up_adc_common.v
add_fileset_file up_axi.v VERILOG PATH ../../library/common/up_axi.v
add_fileset_file up_clkgen.v VERILOG PATH ../../library/common/up_clkgen.v
add_fileset_file up_clock_mon.v VERILOG PATH ../../library/common/up_clock_mon.v
add_fileset_file up_dac_channel.v VERILOG PATH ../../library/common/up_dac_channel.v
add_fileset_file up_dac_common.v VERILOG PATH ../../library/common/up_dac_common.v
add_fileset_file up_delay_cntrl.v VERILOG PATH ../../library/common/up_delay_cntrl.v
add_fileset_file up_hdmi_rx.v VERILOG PATH ../../library/common/up_hdmi_rx.v
add_fileset_file up_hdmi_tx.v VERILOG PATH ../../library/common/up_hdmi_tx.v
add_fileset_file up_pmod.v VERILOG PATH ../../library/common/up_pmod.v
add_fileset_file up_tdd_cntrl.v VERILOG PATH ../../library/common/up_tdd_cntrl.v
add_fileset_file up_xfer_cntrl.v VERILOG PATH ../../library/common/up_xfer_cntrl.v
add_fileset_file up_xfer_status.v VERILOG PATH ../../library/common/up_xfer_status.v
add_fileset_file util_axis_upscale.v VERILOG PATH ../../library/common/util_axis_upscale.v
add_fileset_file util_dec256sinc24b.v VERILOG PATH ../../library/common/util_dec256sinc24b.v
add_fileset_file util_delay.v VERILOG PATH ../../library/common/util_delay.v
add_fileset_file util_pulse_gen.v VERILOG PATH ../../library/common/util_pulse_gen.v
add_fileset_file ad_dcfilter.v VERILOG PATH ../../library/intel/common/ad_dcfilter.v
add_fileset_file ad_mul.v VERILOG PATH ../../library/intel/common/ad_mul.v


# 
# parameters
# 
add_parameter FPGA_TECHNOLOGY STRING CYCLONE5
set_parameter_property FPGA_TECHNOLOGY DEFAULT_VALUE CYCLONE5
set_parameter_property FPGA_TECHNOLOGY DISPLAY_NAME FPGA_TECHNOLOGY
set_parameter_property FPGA_TECHNOLOGY TYPE STRING
set_parameter_property FPGA_TECHNOLOGY UNITS None
set_parameter_property FPGA_TECHNOLOGY HDL_PARAMETER true


# 
# display items
# 


# 
# connection point altera_axi4lite_slave
# 
add_interface altera_axi4lite_slave axi4lite end
set_interface_property altera_axi4lite_slave associatedClock s_axi_clock
set_interface_property altera_axi4lite_slave associatedReset s_axi_reset
set_interface_property altera_axi4lite_slave readAcceptanceCapability 1
set_interface_property altera_axi4lite_slave writeAcceptanceCapability 1
set_interface_property altera_axi4lite_slave combinedAcceptanceCapability 1
set_interface_property altera_axi4lite_slave readDataReorderingDepth 1
set_interface_property altera_axi4lite_slave bridgesToMaster ""
set_interface_property altera_axi4lite_slave ENABLED true
set_interface_property altera_axi4lite_slave EXPORT_OF ""
set_interface_property altera_axi4lite_slave PORT_NAME_MAP ""
set_interface_property altera_axi4lite_slave CMSIS_SVD_VARIABLES ""
set_interface_property altera_axi4lite_slave SVD_ADDRESS_GROUP ""

add_interface_port altera_axi4lite_slave s_axi_awvalid awvalid Input 1
add_interface_port altera_axi4lite_slave s_axi_awaddr awaddr Input 16
add_interface_port altera_axi4lite_slave s_axi_awprot awprot Input 3
add_interface_port altera_axi4lite_slave s_axi_awready awready Output 1
add_interface_port altera_axi4lite_slave s_axi_wvalid wvalid Input 1
add_interface_port altera_axi4lite_slave s_axi_wdata wdata Input 32
add_interface_port altera_axi4lite_slave s_axi_wstrb wstrb Input 4
add_interface_port altera_axi4lite_slave s_axi_wready wready Output 1
add_interface_port altera_axi4lite_slave s_axi_bvalid bvalid Output 1
add_interface_port altera_axi4lite_slave s_axi_bresp bresp Output 2
add_interface_port altera_axi4lite_slave s_axi_bready bready Input 1
add_interface_port altera_axi4lite_slave s_axi_arvalid arvalid Input 1
add_interface_port altera_axi4lite_slave s_axi_araddr araddr Input 16
add_interface_port altera_axi4lite_slave s_axi_arprot arprot Input 3
add_interface_port altera_axi4lite_slave s_axi_arready arready Output 1
add_interface_port altera_axi4lite_slave s_axi_rvalid rvalid Output 1
add_interface_port altera_axi4lite_slave s_axi_rdata rdata Output 32
add_interface_port altera_axi4lite_slave s_axi_rresp rresp Output 2
add_interface_port altera_axi4lite_slave s_axi_rready rready Input 1


# 
# connection point s_axi_clock
# 
add_interface s_axi_clock clock end
set_interface_property s_axi_clock clockRate 0
set_interface_property s_axi_clock ENABLED true
set_interface_property s_axi_clock EXPORT_OF ""
set_interface_property s_axi_clock PORT_NAME_MAP ""
set_interface_property s_axi_clock CMSIS_SVD_VARIABLES ""
set_interface_property s_axi_clock SVD_ADDRESS_GROUP ""

add_interface_port s_axi_clock s_axi_aclk clk Input 1


# 
# connection point s_axi_reset
# 
add_interface s_axi_reset reset end
set_interface_property s_axi_reset associatedClock s_axi_clock
set_interface_property s_axi_reset synchronousEdges DEASSERT
set_interface_property s_axi_reset ENABLED true
set_interface_property s_axi_reset EXPORT_OF ""
set_interface_property s_axi_reset PORT_NAME_MAP ""
set_interface_property s_axi_reset CMSIS_SVD_VARIABLES ""
set_interface_property s_axi_reset SVD_ADDRESS_GROUP ""

add_interface_port s_axi_reset s_axi_aresetn reset_n Input 1


# 
# connection point data_if
# 
add_interface data_if conduit end
set_interface_property data_if associatedClock ""
set_interface_property data_if associatedReset ""
set_interface_property data_if ENABLED true
set_interface_property data_if EXPORT_OF ""
set_interface_property data_if PORT_NAME_MAP ""
set_interface_property data_if CMSIS_SVD_VARIABLES ""
set_interface_property data_if SVD_ADDRESS_GROUP ""

add_interface_port data_if rx_clk_p_in rx_clk_p Input 1
add_interface_port data_if frame_p_in frame_p Input 1
add_interface_port data_if data_p_in data_p Input 6
add_interface_port data_if data_n_in data_n Input 6
add_interface_port data_if frame_n_in frame_n Input 1
add_interface_port data_if rx_clk_n_in rx_clk_n Input 1


# 
# connection point iq_data_out
# 
add_interface iq_data_out conduit end
set_interface_property iq_data_out associatedClock ""
set_interface_property iq_data_out associatedReset ""
set_interface_property iq_data_out ENABLED true
set_interface_property iq_data_out EXPORT_OF ""
set_interface_property iq_data_out PORT_NAME_MAP ""
set_interface_property iq_data_out CMSIS_SVD_VARIABLES ""
set_interface_property iq_data_out SVD_ADDRESS_GROUP ""

add_interface_port iq_data_out re_data_out real Output 16
add_interface_port iq_data_out im_data_out im Output 16


# 
# connection point clk_out
# 
add_interface clk_out clock start
set_interface_property clk_out associatedDirectClock ""
set_interface_property clk_out clockRate 0
set_interface_property clk_out clockRateKnown false
set_interface_property clk_out ENABLED true
set_interface_property clk_out EXPORT_OF ""
set_interface_property clk_out PORT_NAME_MAP ""
set_interface_property clk_out CMSIS_SVD_VARIABLES ""
set_interface_property clk_out SVD_ADDRESS_GROUP ""

add_interface_port clk_out l_clk_out clk Output 1


# 
# connection point reset_source
# 
add_interface reset_source reset start
set_interface_property reset_source associatedClock s_axi_clock
set_interface_property reset_source associatedDirectReset ""
set_interface_property reset_source associatedResetSinks ""
set_interface_property reset_source synchronousEdges DEASSERT
set_interface_property reset_source ENABLED true
set_interface_property reset_source EXPORT_OF ""
set_interface_property reset_source PORT_NAME_MAP ""
set_interface_property reset_source CMSIS_SVD_VARIABLES ""
set_interface_property reset_source SVD_ADDRESS_GROUP ""

add_interface_port reset_source rst_out reset Output 1


# 
# connection point device_clock
# 
add_interface device_clock clock end
set_interface_property device_clock clockRate 0
set_interface_property device_clock ENABLED true
set_interface_property device_clock EXPORT_OF ""
set_interface_property device_clock PORT_NAME_MAP ""
set_interface_property device_clock CMSIS_SVD_VARIABLES ""
set_interface_property device_clock SVD_ADDRESS_GROUP ""

add_interface_port device_clock clk_in clk Input 1

